#!/usr/bin/env python3
"""Build a static Expo asset map for HSK audio files."""

from __future__ import annotations

import argparse
import json
import os
import posixpath
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "assets" / "audio" / "hsk_audio_manifest.json"
DEFAULT_OUTPUT = ROOT / "src" / "data" / "hskAudioAssets.js"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate static require() entries for HSK MP3 assets.")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    items = sorted(manifest.get("items", []), key=lambda item: item.get("hanzi") or "")
    lines = [
        "// Generated by scripts/build_hsk_audio_asset_map.py.",
        "// Do not edit by hand.",
        "",
        "const hskAudioAssets = {",
    ]

    for item in items:
        hanzi = item.get("hanzi")
        file_path = item.get("file")

        if not hanzi or not file_path:
            continue

        relative_path = os.path.relpath(Path(file_path), args.output.parent)
        require_path = posixpath.join(*Path(relative_path).parts)
        lines.append(f"    {json.dumps(hanzi, ensure_ascii=False)}: require({json.dumps(require_path, ensure_ascii=False)}),")

    lines.extend(
        [
            "};",
            "",
            "export default hskAudioAssets;",
            "",
        ]
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(items)} audio asset entries to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
